### ISSUE TITLE
`create_github_check': Forbidden (RuntimeError) in Vic2ToHoI4

### ISSUE THREAD

**Issue by IhateTrains** [cwtools/cwtools-action#7]
```
Tool 'cwtools.cli' (version '0.0.15') was successfully installed.
Cloning into '/src/cwtools-hoi4-config'...
Using metadata cache from 'cwtools/cwtools-cache-files'...
If git fails here, it is most likely because the selected game (hoi4) is not yet supported in the 'cwtools/cwtools-cache-files'. In that case, use CWTools.CLI to generate a full cache of selected game and set it with the cache parameter. Consult README for more information.
Cloning into 'cwtools-cache-files'...
renamed 'cwtools-cache-files/hoi4.cwv.bz2' -> './hoi4.cwv.bz2'
CWTOOLS CHECK
CI ENVIROMENT: github
Is pull request...
Annotating only changed files...
"{\"message\":\"Resource not accessible by integration\",\"documentation_url\":\"https://docs.github.com/rest/reference/checks#create-a-check-run\"}"
/action/lib/cwtools.rb:138:in `create_github_check': Forbidden (RuntimeError)
	from /action/lib/cwtools.rb:303:in `run_github'
	from /action/lib/cwtools.rb:326:in `run'
	from /action/lib/cwtools.rb:333:in `<main>'
```
Full log:
https://github.com/ParadoxGameConverters/Vic2ToHoI4/pull/972/checks?check_run_id=2493040090

Here's the workflow:
```
name: CWTools CI

on: [pull_request, push] # other events may work but are not supported

jobs:
  cwtools_job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1 # required
    - uses: cwtools/cwtools-action@v1.0.0
      with:
        game: hoi4
        modPath: "Vic2ToHoI4/Data_Files/blankMod/output"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

What might be causing this?

**Comment by soryy708** [comment]
Probably the github token is missing permissions.

https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions

Try adding:

```
permissions:
  checks: write
  contents: read
  statuses: write
```
